### ISSUE TITLE
Does not work when using the webpack-dev-server API

### ISSUE THREAD

**Issue by nelix** [qimingweng/static-render-react-hot#1]
The html files don't seem available when using the node API, they are however working correctly if called with the same config via `require('webpack-dev-server/bin/webpack-dev-server')`

@qimingweng had mentioned this might be related to https://github.com/webpack/webpack-dev-server/issues/106

**Comment by qimingweng** [comment]
@nelix Actually I just tested it with my configuration and it seems to be working fine. Do you have a breaking test case you can show?

Are you using any other tools that could be breaking it? Things like react-hot-loader, etc...

**Comment by nelix** [comment]
I just noticed I put this in the wrong repo! Sorry!

**Comment by nelix** [comment]
I gotta run, I'll make something from scratch to demo the issue in isolation later.

**Comment by qimingweng** [comment]
Cool, I'll close this issue on this repo for now.
